"""Dedicated request budgeter for background (Tier 2) work.

Backgrounds are generated by a slow batch pipeline that must never compete
with real-time chat. This budgeter is intentionally separate from the chat
path: it caps background generations with a rolling per-minute burst limit
and a daily quota, and reports its state for ``/v1/status``.

A limit of ``0`` disables that dimension (unlimited). The clock sources are
injectable so the behaviour is deterministic under test.
"""

from __future__ import annotations

import time
from collections import deque
from collections.abc import Callable
from typing import Any


class BackgroundBudgeter:
    """Sliding-window + daily quota for background generations."""

    def __init__(
        self,
        *,
        per_minute: int = 6,
        daily: int = 120,
        monotonic: Callable[[], float] = time.monotonic,
        wall_clock: Callable[[], float] = time.time,
    ) -> None:
        self._per_minute = max(0, int(per_minute))
        self._daily = max(0, int(daily))
        self._monotonic = monotonic
        self._wall = wall_clock
        self._window: deque[float] = deque()
        self._day = self._day_key()
        self._day_used = 0
        self._total_used = 0

    def _day_key(self) -> str:
        return time.strftime("%Y-%m-%d", time.gmtime(self._wall()))

    def _prune(self, now: float) -> None:
        cutoff = now - 60.0
        while self._window and self._window[0] <= cutoff:
            self._window.popleft()

    def _roll_day(self) -> None:
        today = self._day_key()
        if today != self._day:
            self._day = today
            self._day_used = 0

    def try_acquire(self) -> bool:
        """Consume one slot; return False when any active limit is reached."""
        now = self._monotonic()
        self._prune(now)
        self._roll_day()

        if self._per_minute > 0 and len(self._window) >= self._per_minute:
            return False
        if self._daily > 0 and self._day_used >= self._daily:
            return False

        self._window.append(now)
        self._day_used += 1
        self._total_used += 1
        return True

    def refund(self) -> None:
        """Return the most recent slot.

        The pipeline refunds when a job did not actually call an LLM (template
        fallback or a cache hit), so the budget meters real provider usage.
        """
        if self._window:
            self._window.pop()
        if self._day_used > 0:
            self._day_used -= 1
        if self._total_used > 0:
            self._total_used -= 1

    def snapshot(self) -> dict[str, Any]:
        """Return a JSON-serializable view of the current budget usage."""
        now = self._monotonic()
        self._prune(now)
        self._roll_day()
        return {
            "per_minute": self._per_minute,
            "daily_limit": self._daily,
            "minute_used": len(self._window),
            "day_used": self._day_used,
            "day_remaining": None if self._daily <= 0 else max(0, self._daily - self._day_used),
            "total_used": self._total_used,
        }

    def reset(self) -> None:
        """Clear all tracked usage (used on a full reset)."""
        self._window.clear()
        self._day_used = 0
        self._total_used = 0
        self._day = self._day_key()
