# Sensewright v2 — Tuning ID Resolution (Python 3.7 compatible)
# Resolves Sensewright-owned tuning IDs (trait, dream buffs, missing-player
# moodlet) and native TS4 tuning IDs (moods, sentiments, weather) and registers
# them with native_hooks / tool_executor at startup.
#
# Owned tunings use TS4's canonical instance convention: FNV-1 64-bit of the
# tuning name (lowercased) with the high bit set — identical to S4CL's
# `CommonResourceUtils.convert_str_to_fnv64` and to what `build_package.py`
# emits into `tuning_ids.json`. When the compiled `tuning_ids.json` is present
# inside the .ts4script it is treated as the single source of truth.

import json
import os
import zipfile

from sensewright_mod.debug_log import log_debug, log_exception, log_info

# FNV-1 64-bit constants (TS4 tuning instance convention).
_FNV64_OFFSET = 14695981039346656037
_FNV64_PRIME = 1099511628211
_FNV64_MASK = 0xFFFFFFFFFFFFFFFF
_FNV64_HIGH_BIT = 0x8000000000000000

# Sensewright-owned tuning names (must match the `n` attribute in tuning/*.xml).
_OWNED_NAMES = {
    "trait_hidden_no_walkby": "Trait_Hidden_NoWalkby",
    "buff_dream_epiphany": "buff_dream_epiphany",
    "buff_dream_surreal": "buff_dream_surreal",
    "buff_dream_omen": "buff_dream_omen",
    "buff_dream_nightmare": "buff_dream_nightmare",
    "buff_missing_player": "buff_missing_player",
    "interaction_chat": "sw_chat_interaction",
    "interaction_provoke": "sw_provoke_interaction",
    "interaction_panel": "sw_panel_interaction",
    # Autonomy-bias buffs (generated by tools/gen_bias_buffs.py). Each adds a
    # base-game `commodity_Trait_Autonomy_*` so native autonomy seeks the
    # matching activities (REQ-COG-02 / M5).
    "bias_active": "buff_bias_active",
    "bias_art": "buff_bias_art",
    "bias_creative": "buff_bias_creative",
    "bias_family": "buff_bias_family",
    "bias_focused": "buff_bias_focused",
    "bias_foodie": "buff_bias_foodie",
    "bias_geek": "buff_bias_geek",
    "bias_music": "buff_bias_music",
    "bias_neat": "buff_bias_neat",
    "bias_outdoors": "buff_bias_outdoors",
    "bias_playful": "buff_bias_playful",
    "bias_read": "buff_bias_read",
    "bias_romantic": "buff_bias_romantic",
    "bias_social": "buff_bias_social",
}

_tuning_ids_cache = None
_tuning_ids_loaded = False


def fnv1_64(text):
    """FNV-1 64-bit hash with high bit set (TS4 tuning instance ID)."""
    h = _FNV64_OFFSET
    for byte in text.lower().encode("utf-8"):
        h = (h * _FNV64_PRIME) & _FNV64_MASK
        h ^= byte
    return h | _FNV64_HIGH_BIT


def _find_mod_zip():
    """Locate the installed Sensewright.ts4script zip file."""
    mod_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for root, dirs, files in os.walk(os.path.dirname(mod_dir)):
        for name in files:
            if name.lower().startswith("sensewright") and name.endswith(".ts4script"):
                return os.path.join(root, name)
    return None


def _load_tuning_ids():
    """Load tuning_ids.json from the .ts4script zip (single source of truth)."""
    global _tuning_ids_cache, _tuning_ids_loaded
    if _tuning_ids_loaded:
        return _tuning_ids_cache
    _tuning_ids_loaded = True

    zip_path = _find_mod_zip()
    if zip_path is None:
        log_debug("tuning: no .ts4script found; falling back to FNV-64")
        return None

    try:
        with zipfile.ZipFile(zip_path, "r") as zf:
            if "sensewright_mod/tuning_ids.json" in zf.namelist():
                with zf.open("sensewright_mod/tuning_ids.json") as fh:
                    data = json.load(fh)
                _tuning_ids_cache = data
                log_debug("tuning: loaded {} owned ids from {}".format(
                    len(data.get("tunings", {})), zip_path))
                return data
    except Exception as e:
        log_exception("tuning: failed to load tuning_ids.json: {}".format(e))

    return None


def owned_bias_keys():
    """Tuning keys for the generated autonomy-bias buffs (used by diagnostics)."""
    return sorted(key for key in _OWNED_NAMES if key.startswith("bias_"))


def resolve_owned_id(key):
    """Resolve a Sensewright-owned tuning ID (from tuning_ids.json or FNV-64)."""
    name = _OWNED_NAMES.get(key)
    if name is None:
        return 0

    data = _load_tuning_ids()
    if data:
        tunings = data.get("tunings", {})
        if name in tunings:
            try:
                return int(tunings[name])
            except (TypeError, ValueError):
                pass

    return fnv1_64(name)


def _native_mood_map():
    """semantic mood -> Types.MOOD id (verified from S4CL CommonMoodId)."""
    try:
        from sims4communitylib.enums.moods_enum import CommonMoodId as M
        return {
            "fine": int(M.FINE),
            "flirty": int(M.FLIRTY),
            "tense": int(M.STRESSED),
            "sad": int(M.SAD),
            "angry": int(M.ANGRY),
            "inspired": int(M.INSPIRED),
            "uncomfortable": int(M.UNCOMFORTABLE),
            "dazed": int(M.DAZED),
            "happy": int(M.HAPPY),
            "confident": int(M.CONFIDENT),
            "focused": int(M.FOCUSED),
            "playful": int(M.PLAYFUL),
            "energized": int(M.ENERGIZED),
            "bored": int(M.BORED),
            "embarrassed": int(M.EMBARRASSED),
            "scared": int(M.SCARED),
        }
    except Exception as e:
        log_debug("tuning: mood enums unavailable: {}".format(e))
        return {}


def _native_sentiment_map():
    """semantic sentiment -> relationship bit id (verified from S4CL CommonRelationshipBitId)."""
    try:
        from sims4communitylib.enums.relationship_bits_enum import CommonRelationshipBitId as S
        return {
            "adoring": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_ADORING),
            "adoration": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_ADORING),
            "bitter": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_BITTER),
            "grudge": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_BITTER),
            "close": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_CLOSE),
            "closeness": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_CLOSE),
            "enamored": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_ENAMORED),
            "furious": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_FURIOUS),
            "guilty": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_GUILTY),
            "hurt": int(S.RELATIONSHIP_BIT_COLLECTION_SENTIMENT_HURT),
        }
    except Exception as e:
        log_debug("tuning: sentiment enums unavailable: {}".format(e))
        return {}


def _native_weather_map():
    """semantic weather -> weather event id (verified from S4CL CommonWeatherEventId).

    NOTE: weather levers require the Seasons EP (REQ-GOD-02 / A10).
    """
    try:
        from sims4communitylib.enums.common_weather_event_ids import CommonWeatherEventId as W
        return {
            "clear": int(W.CLEAR),
            "sunny": int(W.CLEAR),
            "rain": int(W.RAIN_LIGHT_WARM),
            "snow": int(W.SNOW_LIGHT_FREEZING),
            "thunderstorm": int(W.RAINSTORM_WARM),
            "storm": int(W.RAINSTORM_WARM),
        }
    except Exception as e:
        log_debug("tuning: weather enums unavailable: {}".format(e))
        return {}


def register_all_tuning():
    """Resolve and register all tuning IDs with native_hooks / tool_executor."""
    from sensewright_mod.native_hooks import (
        register_tuning_ids, register_missing_player_buff
    )
    from sensewright_mod.tool_executor import register_archetype_mappings

    trait = resolve_owned_id("trait_hidden_no_walkby")
    epiphany = resolve_owned_id("buff_dream_epiphany")
    surreal = resolve_owned_id("buff_dream_surreal")
    omen = resolve_owned_id("buff_dream_omen")
    nightmare = resolve_owned_id("buff_dream_nightmare")
    missing_player = resolve_owned_id("buff_missing_player")

    register_tuning_ids(
        trait_hidden_nowalkby=trait,
        buff_dream_epiphany=epiphany,
        buff_dream_surreal=surreal,
        buff_dream_omen=omen,
        buff_dream_nightmare=nightmare,
        bias_commodity_buffs={},
    )
    register_missing_player_buff(missing_player)

    # Archetype -> bias buff. Each buff is a hidden moodlet that adds the
    # matching base-game autonomy commodity, steering native autonomy.
    bias_buffs = {
        key[len("bias_"):]: resolve_owned_id(key)
        for key in _OWNED_NAMES
        if key.startswith("bias_")
    }

    register_archetype_mappings(
        mood_map=_native_mood_map(),
        activity_map={},
        sentiment_map=_native_sentiment_map(),
        weather_map=_native_weather_map(),
        archetype_map={},
        bias_buffs=bias_buffs,
    )

    log_info("tuning: registered owned ids (trait={}, dream_buffs={}/{}/{}/{}, missing_player={}, bias_buffs={})".format(
        trait, epiphany, surreal, omen, nightmare, missing_player, len(bias_buffs)))
