#!/usr/bin/env python3
"""Generate Sensewright autonomy-bias Buff tunings from extracted game data.

Native TS4 autonomy is steered by hidden *commodity* statistics. Traits such as
Creative work by adding `commodity_Trait_Autonomy_*` commodities through a
Buff's `game_effect_modifiers.autonomy_modifier.commodities_to_add` list. This
tool turns the extracted commodity table into one hidden Sensewright bias Buff
per archetype, so `bias_interaction` intents get a real, native effect instead
of only nudging a mood.

Pipeline:
  1. tools/dbpf_tool.py extract <game Simulation .package> --type combined_tuning
  2. tools/dbpf_tool.py autonomy <combined.xml> --out research/game_tuning/autonomy_commodities.json
  3. tools/gen_bias_buffs.py --autonomy-json <...> --out mod/tuning/buffs

The generated XML is committed; re-run only when the game's tuning changes.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

BUFF_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/gen_bias_buffs.py from {commodity} ({commodity_id}). -->
<I c="Buff" i="buff" m="buffs.buff" n="{tuning_name}" s="0">
  <E n="buff_type">POSITIVE</E>
  <T n="duration">{duration}</T>
  <T n="mood_type">0</T>
  <T n="mood_weight">0</T>
  <T n="visible">False</T>
  <U n="game_effect_modifiers">
    <L n="game_effect_modifiers">
      <V t="autonomy_modifier">
        <U n="autonomy_modifier">
          <L n="commodities_to_add">
            <r>{commodity_id}</r>
          </L>
        </U>
      </V>
    </L>
  </U>
  <V n="buff_name" t="localized_string" p="STBL">stbl.{stbl_key}.name</V>
  <V n="buff_description" t="localized_string" p="STBL">stbl.{stbl_key}.desc</V>
  <V n="tooltip" t="localized_string" p="STBL">stbl.{stbl_key}.desc</V>
</I>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate autonomy-bias buff tunings")
    parser.add_argument("--autonomy-json", required=True,
                        help="autonomy_commodities.json produced by dbpf_tool.py autonomy")
    parser.add_argument("--bias-map", default=str(Path(__file__).with_name("bias_map.json")))
    parser.add_argument("--out", required=True, help="directory for the generated buff XMLs")
    parser.add_argument("--duration", type=int, default=240, help="buff duration in sim minutes")
    args = parser.parse_args()

    autonomy = json.loads(Path(args.autonomy_json).read_text(encoding="utf-8"))
    bias_map = json.loads(Path(args.bias_map).read_text(encoding="utf-8"))

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    archetype_buffs = {}
    for archetype, spec in sorted(bias_map.items()):
        commodity = spec["commodity"]
        commodity_id = autonomy.get(commodity)
        if commodity_id is None:
            raise SystemExit("unknown autonomy commodity: {}".format(commodity))
        tuning_name = "buff_bias_{}".format(archetype)
        body = BUFF_TEMPLATE.format(
            commodity=commodity, commodity_id=commodity_id,
            tuning_name=tuning_name, duration=args.duration,
            stbl_key="buff.bias_{}".format(archetype),
        )
        (out / (tuning_name + ".xml")).write_text(body, encoding="utf-8")
        for alias in spec.get("aliases", []):
            archetype_buffs[alias] = tuning_name
        archetype_buffs[archetype] = tuning_name
        print("  {} -> {} (commodity {} = {})".format(archetype, tuning_name, commodity, commodity_id))

    # Emit the archetype->tuning mapping consumed by tuning.py's registration.
    mapping_path = out / "bias_buffs.json"
    mapping_path.write_text(
        json.dumps(archetype_buffs, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print("wrote {} buffs and {}".format(len(bias_map), mapping_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
