#!/usr/bin/env python3
# Sensewright v2 — Build Script for .ts4script
# Python 3.10+ (build machine), produces Python 3.7 bytecode

import os
import sys
import zipfile
import shutil
import subprocess
import tempfile
from pathlib import Path


MOD_DIR = Path(__file__).parent
SRC_DIR = MOD_DIR / "sensewright_mod"
DIST_DIR = MOD_DIR / "dist"
DIST_DIR.mkdir(exist_ok=True)

OUTPUT_SCRIPT = DIST_DIR / "Sensewright.ts4script"

# Python 3.7 magic number: 42 0d 0d 0a (0x0a0d0d42 little-endian)
PY37_MAGIC = b"\x42\x0d\x0d\x0a"


def verify_python37():
    """Verify we're using Python 3.7 for compilation."""
    if sys.platform == "win32":
        try:
            result = subprocess.run(["py", "-3.7", "--version"], capture_output=True, text=True)
            if result.returncode == 0 and "3.7" in result.stdout:
                print("Found Python 3.7: {}".format(result.stdout.strip()))
                return ["py", "-3.7"]
        except Exception:
            pass
    else:
        try:
            result = subprocess.run(["python3.7", "--version"], capture_output=True, text=True)
            if result.returncode == 0 and "3.7" in result.stdout:
                print("Found Python 3.7: {}".format(result.stdout.strip()))
                return ["python3.7"]
        except Exception:
            pass

    print("ERROR: Python 3.7 not found. Please install Python 3.7.9")
    print("The .ts4script must be compiled with Python 3.7 bytecode (magic 42 0d 0d 0a)")
    sys.exit(1)


def compile_python37(python_cmd, source_dir, output_dir):
    """Compile each source file straight to its destination .pyc.

    Earlier this relied on py_compile's shared ``__pycache__`` directory and
    then moved *every* ``*.pyc`` it found into the current output file. Because
    all modules in a package share one ``__pycache__``, a non-empty cache would
    overwrite one module with another module's bytecode (e.g. chat_ui.pyc
    containing pie_menu bytecode), producing ImportErrors in-game. Compiling
    with an explicit ``cfile`` guarantees the correct module/bytecode pairing.
    """
    print("Compiling with {}...".format(" ".join(python_cmd)))

    compile_snippet = (
        "import py_compile, sys; "
        "py_compile.compile(sys.argv[1], cfile=sys.argv[2], doraise=True)"
    )
    for py_file in source_dir.rglob("*.py"):
        rel_path = py_file.relative_to(source_dir)
        out_file = output_dir / rel_path.with_suffix(".pyc")
        out_file.parent.mkdir(parents=True, exist_ok=True)

        result = subprocess.run(
            python_cmd + ["-c", compile_snippet, str(py_file), str(out_file)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print("ERROR compiling {}:".format(py_file))
            print(result.stderr)
            return False

    # Clean up any stale __pycache__ directories left in the source tree.
    for pycache in source_dir.rglob("__pycache__"):
        shutil.rmtree(pycache, ignore_errors=True)

    return True


def verify_bytecode_magic(pyc_dir):
    """Verify all .pyc files have Python 3.7 magic number."""
    print("Verifying bytecode magic numbers...")
    for pyc_file in pyc_dir.rglob("*.pyc"):
        with open(pyc_file, "rb") as f:
            magic = f.read(4)
            if magic != PY37_MAGIC:
                print("ERROR: {} has wrong magic number: {}".format(pyc_file, magic.hex()))
                print("Expected: {}".format(PY37_MAGIC.hex()))
                return False
    print("All .pyc files have correct Python 3.7 magic number")
    return True


def create_ts4script(compiled_dir, output_path):
    """Create the .ts4script zip file."""
    print("Creating .ts4script: {}".format(output_path))

    # TS4 treats the .ts4script as a directory whose entries map to dotted
    # module names. The package folder MUST be present inside the zip (like
    # S4CL's `sims4communitylib/...`), otherwise `import sensewright_mod`
    # fails and the game imports every .pyc as a top-level module.
    with zipfile.ZipFile(output_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for pyc_file in compiled_dir.rglob("*.pyc"):
            arcname = "sensewright_mod/{}".format(pyc_file.relative_to(compiled_dir))
            zf.write(pyc_file, arcname)

        # Include locale JSON files (manifest + ui/*.json)
        locales_dir = MOD_DIR / "sensewright_mod" / "locales"
        for locale_file in locales_dir.rglob("*.json"):
            arcname = "sensewright_mod/locales/{}".format(locale_file.relative_to(locales_dir))
            zf.write(locale_file, arcname)

        # Include tuning_ids.json (generated by build_package.py) when available.
        tuning_ids_path = DIST_DIR / "tuning_ids.json"
        if tuning_ids_path.exists():
            zf.write(tuning_ids_path, "sensewright_mod/tuning_ids.json")

    print("Created: {} ({} bytes)".format(output_path, output_path.stat().st_size))
    return True


def main():
    print("=" * 60)
    print("Sensewright v2 — Build .ts4script")
    print("=" * 60)

    python_cmd = verify_python37()

    with tempfile.TemporaryDirectory() as tmpdir:
        compiled_dir = Path(tmpdir) / "compiled"
        compiled_dir.mkdir()

        if not compile_python37(python_cmd, SRC_DIR, compiled_dir):
            sys.exit(1)

        if not verify_bytecode_magic(compiled_dir):
            sys.exit(1)

        if not create_ts4script(compiled_dir, OUTPUT_SCRIPT):
            sys.exit(1)

    print("=" * 60)
    print("Build successful!")
    print("Output: {}".format(OUTPUT_SCRIPT))
    print("=" * 60)


if __name__ == "__main__":
    main()